---
- hosts: all
  become: true
  tasks:
    - name: "Update etc/hosts"
      lineinfile:
        path: /etc/hosts
        line: '{{ item }}'
      with_items:
        - '192.168.56.3  bastion'
        - '192.168.56.11 node-1 zabbix-web zabbix-server zabbix.example.com'
        - '192.168.56.12 node-2 zabbix-database'
        - '192.168.56.13 node-3 zabbix-proxy'

    - name: Install basic packages
      apt:
        name:
          - ca-certificates
          - curl
          - python3
          - python3-pip
          - git
        state: present
        update_cache: True

    - name: "Install Python modules"
      pip:
        name: 
          - ansible
          - netaddr
          - zabbix-api
        state: present

    - name: "generate SSH key"
      openssh_keypair:
        path: "/home/vagrant/.ssh/id_rsa"
        type: rsa
        size: 4096
        state: present
        force: no

    - name: "Own the id_rsa* file"
      file:
        path: "/home/vagrant/{{ item }}"
        owner: vagrant
        group: vagrant
        mode: 0400
      with_items:
        - .ssh/id_rsa
        - .ssh/id_rsa.pub

    - name: Specifying a path directly
      fetch:
        src: "/home/vagrant/.ssh/id_rsa.pub"
        dest: id_rsa.pub
        flat: yes

    - name: "Set timezone to Europe/Amsterdam"
      community.general.timezone:
        name: Europe/Amsterdam