---
- name: install docker
  hosts: node1
  become: true
  vars:
    create_containers: 1
    default_container_name: docker
    default_container_image: zabbix
    default_container_command: sleep 1d

  tasks:
  - name: Install aptitude using apt
  apt: name = aptitude state = latest update_cache = yes force_apt_get=yes
  - name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools'] - name: Add Docker GPG apt Key
        apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
        apt_repository:
        repo: deb https://hub.docker.com/r/ibmcom/zabbix-server-s390x
        state: present
    - name: Update apt and install docker-ce
        apt: update_cache=yes name=docker-ce state=latest
    - name: Install Docker Module for Python
        pip:
            name: docker
# Pull image specified by variable default_image from the Docker Hub
    - name: Pull default Docker image
        docker_image:
        name: "{{ default_container_image }}"
        source: pull
# Creates the number of containers defined by the variable create_containers, using default values
    - name: Create default containers
        docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
        with_sequence: count={{ create_containers }}

...