---

- name: install docker
  hosts: node3
  become: true
  vars:
    create_containers: 1
    default_container_name: 'test-zabbix-zabbix-appliance'
    #default_container_image: 'zabbix/zabbix-server-mysql'
    default_container_image: 'zabbix/zabbix-appliance'
    default_container_command: sleep 1d
    

  tasks:
          
    #- name: Install python3-apt (python 3) using apt
    #  apt: 
    #   name: python3-apt 
    #   state: latest 
    
     
    - name: Add Docker GPG apt Key
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    
    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic
        state: present
        
    - name: Install Docker Module for Python
      pip:
          name: docker

    - name: Log into DockerHub
      docker_login:
       username: kireevart
       password: Rainnyday22

       
# Pull image specified by variable default_image from the Docker Hub
    - name: Pull default Docker image "{{ default_container_image }}"
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
        
# Creates the number of containers defined by the variable create_containers, using default values
    - name: Create default containers
      docker_container:
          name: "{{ default_container_name }}"
          image: "{{ default_container_image }}"
          command: "{{ default_container_command }}"
          detach: yes
          tty: yes
          ports:
            - "80:80"
            - "10051:10051"
          state: present
         

    #- name: Start Docker container
    #  community.docker.docker_compose:
    #    restarted: yes
    #    state: present
        
        
    #- name: Install aptitude using apt
    #  apt: 
    #   name: aptitude 
    #   state: latest 
    
    #- name: Install basic packages
    #  apt:
    #   name:
    #     - apt-transport-https
    #     - curl
    #     - python3
    #     - python3-pip
    #     - python3-dnf
    #     - git
    #     - ca-certificates
    #     - software-properties-common
    #     - virtualenv
    #     - python3-setuptools
    #     - docker-ce
    #     - docker-ce-cli
    #     - containerd.io
    #   #state: present
    #   state: latest
    #   update_cache: false
        
            
    #- name: Install Docker
    #  ansible.builtin.yum:
    #    name:
    #      - docker-ce
    #      - docker-ce-cli
    #      - containerd.io
    #    use_backend: dnf
    #    state: present
    #    update_cache: true     
        
...